### ISSUE TITLE
Add docs informations

### ISSUE THREAD

**Issue by Maxlego08** [Azuriom/azuriom.com#20]
Add information on how to check if a plugin is active.

`plugins()->isEnabled(<plugin name>)`

**Comment by Micorksen** [comment]
Hello, you need to issue here : https://github.com/Azuriom/Azuriom.0

**Comment by Maxlego08** [comment]
> Hello, you need to issue here : https://github.com/Azuriom/Azuriom.

The issue is made for a modification of the documentation, so I am well in the right repo.

**Comment by MrMicky-FR** [comment]
Closing in favor of #60
