### ISSUE TITLE
Market : Notification

### ISSUE THREAD

**Issue by Oxim0v** [Azuriom/azuriom.com#26]
Send a notification with a discord webhook when a resource is published or updated really really practical for theme devs or for the public

**Comment by MrMicky-FR** [comment]
Unfortunately this can’t be added without exposing our IPs address or provisioning additional resources, which we both want to avoid. 

Themes developers are encouraged to have a GitHub repo for their theme, which supports Discord webhook (like we do on Azuriom Discord server, in the changelog channel)
