### ISSUE TITLE
Azlink pocketMine

### ISSUE THREAD

**Issue by SharkZekrom** [Azuriom/azuriom.com#31]
Hello, is there a bug with Azlink pocketmine link

the actual link is wrong :https://github.com/Azuriom/AzLink-PocketMine/releases/download/v1.0.0/AzLink-PocketMine.phar

and the good link is https://github.com/Azuriom/AzLink-PocketMine/releases/download/v1.0.0/AzLink-PocketMine-1.0.0.phar

**Comment by MrMicky-FR** [comment]
Thanks, it’s fixed
