### ISSUE TITLE
TOS Page 404

### ISSUE THREAD

**Issue by thefourcraft** [Azuriom/azuriom.com#37]
# The Bug
https://azuriom.com/en/terms page isn't working.
you can't access to read the TOS 📏

**Comment by MrMicky-FR** [comment]
Hi, this page has been removed, normally all references to this page have also been removed. About the TOS, you can take a look at the [GNU GPL v3.0 license](https://github.com/Azuriom/Azuriom/blob/master/LICENSE) :)
