### ISSUE TITLE
Information about Microsoft login

### ISSUE THREAD

**Issue by 0xBitMC** [Azuriom/azuriom.com#41]
Greetings,

Can you please provide detailed documentation on how Azuriom uses Microsoft Account data with the Microsoft Login feature. A lot of players ask why they need to utilize this and since it is a third-party application, people are often hesitant to use it. 

Information on what information is utilized and how they can remove it after if they so choose.

Thanks,
0xBit

**Comment by MrMicky-FR** [comment]
Hi, Microsoft authentication is only used to provide quick and secure login as it's ensure that the player is the owner of the Minecraft account. The only collected data are the Minecraft username and UUID (or Xbox Gamertag and XUID for Minecraft Bedrock Edition).

To remove these information, players can contact the server admin to delete their account from the website (this can be done in the admin dashboard, in users -> delete).

Tell me if you need more information :)

**Comment by 0xBitMC** [comment]
Hello again,

Would you be willing to put this into an FAQ or Section on your website, so I can directly show users whose application is accessing what information and why?

Thank you,
0xBit.
