### ISSUE TITLE
 Beautify the forum 

### ISSUE THREAD

**Issue by Dotta4You** [Azuriom/azuriom.com#50]
Beautify the forum with round edges, etc. :D

**Comment by MrMicky-FR** [comment]
This should be done in a theme

**Comment by Dotta4You** [comment]
but it looks so weird in all themes :). and deim update theme and many others, the forum is extremely angular xD

**Comment by MrMicky-FR** [comment]
Themes are mostly made by the community, you should see with the theme author if you have any suggestions about this
