### ISSUE TITLE
Dropdowns in Dropdowns

### ISSUE THREAD

**Issue by loothillRw** [Azuriom/azuriom.com#53]
Able to add dropdowns inside dropdowns

Pic example https://prnt.sc/LtrtkxWCPuiK
Sorry couldn't find another example, this one was from my website.

**Comment by MrMicky-FR** [comment]
Hi, thanks for your suggestion, however this should be in the Azuriom/Azuriom repo. Also this feature isn’t planned as nested dropdown are terrible for UX and it would be a nightmare to add this feature to all existing themes
