### ISSUE TITLE
Forum : Tag system

### ISSUE THREAD

**Issue by Lucass27400** [Azuriom/azuriom.com#55]
Add a system to notify a player like @MrMicky-FR it's a very nice update for users to gain some time and not very hard to apply it for you I think

**Comment by n0tMarvin** [comment]
@Lucass27400 

You can notify users already

**Comment by Lucass27400** [comment]
How ? When I put the @ I have nothing

**Comment by MrMicky-FR** [comment]
> How ? When I put the @ I have nothing

You have no notifications when mentioning yourself
