### ISSUE TITLE
Big suggestions :p

### ISSUE THREAD

**Issue by majklfild** [Azuriom/azuriom.com#57]
I wondered if you should add some widgets, similar to discord, for example active members of the team, active members on the website, and I'm also missing a plugin for forms, or a plugin for direct file downloads. I would definitely recommend simplifying the settings of the Staff page. Give users more options, come on! :)

**Comment by lapetitehanae** [comment]
Hello, 

I can make for you a forms & file downloads plugin.
Send me a message: hanaé#2022

**Comment by MrMicky-FR** [comment]
Hi, this GitHub repository is for our website and not for Azuriom itself. Also unfortunately we are not keeping suggestions for entirely new plugins as we prefer focus on adding the suggestions for existing plugins (and there are quite a few!)
