### ISSUE TITLE
Change permission set command

### ISSUE THREAD

**Issue by microwin7** [Azuriom/azuriom.com#67]
https://github.com/search?q=org%3AAzuriom%20chmod%20-R%20755%20%2Fvar%2Fwww%2Fazuriom&type=code
Replace ->
```
find /var/www/azuriom -type d -exec chmod 755 {} \; &&
find /var/www/azuriom -type f -exec chmod 644 {} \;
```
And use `chmod +x /var/www/azuriom/....php` if some script needs to be made executable

**Comment by MrMicky-FR** [comment]
Hi, thank you for this suggestion, could you please provide some details on why this change should be made ? Thanks!
