### ISSUE TITLE
Adding new rule/group

### ISSUE THREAD

**Issue by Shaezee** [Azuriom/azuriom.com#79]
Could be more good if there would be a role Guest. That would be for the ones who haven't created account yet or logged in one.
That would give a permission to use shop/buy things without making account, example like minecraft. Most web store/monetizing systems allow guests to use shop and it makes weird, if player doesn't use forum and only wan't to buy for example a vip  ingame group, he need to register for it. I think registering for using a shop is unnecessary

**Comment by MrMicky-FR** [comment]
This is not the correct the repo for this suggestion. Also there is multiples ways to use automatic registration (with Microsoft for online-mode Minecraft servers or AuthMe/LimboAuth for offline-mode servers) so it’s never required to manually register
